In [1]:
import numpy as np
fare = np.array([50,70,100,150,200])
print(fare)
print(type(fare))

[ 50  70 100 150 200]
<class 'numpy.ndarray'>


In [6]:
#2 dimensional array
day_fares = np.array([
    [60,80,100],
    [56,89,70],
    [40,50,60],
    ])

print(day_fares)
print(day_fares.shape)

[[ 60  80 100]
 [ 56  89  70]
 [ 40  50  60]]
(3, 3)


In [8]:
# Array of constants
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.full((2, 2),7.5)

array([[7.5, 7.5],
       [7.5, 7.5]])

In [13]:
#Ranges
np.arange(0, 10, 2)


array([0, 2, 4, 6, 8])

In [15]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

Arange is for when you know the step size;linspace is for when you know how many values you want and want them evenly spaced .Staticians use linspace all the time to generate x-values for plotting curves

In [16]:
#Identity matrices
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

1. An array of the numbers 5 to 20 inclusive
2. A 4 by 4 matrix of all threes
3. Ten values evenly spaced between 0 and 1
4. The 5 by 5 identity matrix
5. A 2D array representing a week (7rows) of hourly fares(24 columns) all initialized to zero - you will fill this in later

In [23]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [19]:
np.arange(5, 21, 1)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])