### EXERCISE 1

In [1]:
import numpy as np

In [2]:
np.random.seed(42)
daily_sales = np.random.randint(5000, 10000, size=(10, 4))
units_sold = np.random.randint(50, 100, size=(10, 4))

In [3]:

print(f"Sales:{daily_sales.shape}")
print(f"Sales:{daily_sales.ndim}")
print(f"Sales:{daily_sales.size}")
print(f"Sales:{daily_sales.dtype}")

print(f"Units:{units_sold.shape}")
print(f"Units:{units_sold.ndim}")
print(f"Units:{units_sold.size}")
print(f"Units:{units_sold.dtype}")

Sales:(10, 4)
Sales:2
Sales:40
Sales:int32
Units:(10, 4)
Units:2
Units:40
Units:int32


In [4]:
targets = np.full((10, 4), 15000)
print(targets)
print("Properties of targets:")
print(f"Shape: {targets.shape}",)
print(f"Size: {targets[0, 0]}",)
print(f"Dtype: {targets.dtype}")

#What does np.full() do?
#It creates an array and fills every single position with the same value.

[[15000 15000 15000 15000]
 [15000 15000 15000 15000]
 [15000 15000 15000 15000]
 [15000 15000 15000 15000]
 [15000 15000 15000 15000]
 [15000 15000 15000 15000]
 [15000 15000 15000 15000]
 [15000 15000 15000 15000]
 [15000 15000 15000 15000]
 [15000 15000 15000 15000]]
Properties of targets:
Shape: (10, 4)
Size: 15000
Dtype: int64


In [5]:
minimum_sales = daily_sales.min()
maximum_sales = daily_sales.max()
sales_range = np.linspace(minimum_sales, maximum_sales, 10)
print("10 evenly spaced values from minimum to maximum sales:")
print(sales_range)

10 evenly spaced values from minimum to maximum sales:
[5130.         5653.66666667 6177.33333333 6701.         7224.66666667
 7748.33333333 8272.         8795.66666667 9319.33333333 9843.        ]


In [6]:
np.random.seed(7)
simulated_clothing = np.random.normal(loc=9500, scale=1200, size=10)
real_clothing_mean = daily_sales[:, 2].mean()

print(f"Simulated Clothing Mean: {simulated_clothing.mean():.2f}")
print(f"Actual Clothing Mean: {real_clothing_mean:.2f}")

Simulated Clothing Mean: 9588.87
Actual Clothing Mean: 7461.70


### EXERCISE 2

In [7]:
electronics_data = daily_sales[:, 1]
print(electronics_data)
print(f"Max single-day sales for Electronics: {electronics_data.max()}")

[8772 8444 6685 6184 9843 7558 6806 9658 8202 7888]
Max single-day sales for Electronics: 9843


In [8]:
last_3_days_food = daily_sales[-3:, 0]
print(last_3_days_food)
print(f"Average of last 3 days of Food sales: {last_3_days_food.mean():.2f}")

[8005 6528 5646]
Average of last 3 days of Food sales: 6726.33


In [9]:
food_clothing = daily_sales[:5, [0, 2]]
print(food_clothing)
print(f"Shape of 5 day food and clothing: {food_clothing.shape}")

[[5860 8092]
 [9426 8171]
 [5130 5769]
 [7433 9555]
 [9117 7904]]
Shape of 5 day food and clothing: (5, 2)


In [10]:
even_days = daily_sales[::2]
totals_even_days = even_days.sum(axis=0)
print(f"Column totals for even indexed days: {totals_even_days}")

Column totals for even indexed days: [32610 40308 35510 34955]


In [11]:
subgrid_copy = daily_sales[3:6, 1:3].copy()
subgrid_copy += 500

print("Original slice:")
print(daily_sales[3:6, 1:3])

print("Modified copy:")
print(subgrid_copy)

Original slice:
[[6184 9555]
 [9843 7904]
 [7558 7047]]
Modified copy:
[[ 6684 10055]
 [10343  8404]
 [ 8058  7547]]


### EXERCISE 3

In [12]:
vat_rate = 1.16
sales_with_vat = daily_sales * vat_rate
print(sales_with_vat)

[[ 6797.6  10175.52  9386.72  6340.56]
 [10934.16  9795.04  9478.36  9186.04]
 [ 5950.8   7754.6   6692.04  8573.56]
 [ 8622.28  7173.44 11083.8   9726.6 ]
 [10575.72 11417.88  9168.64  6349.84]
 [ 7055.12  8767.28  8174.52  8986.52]
 [ 6931.    7894.96  6019.24  8971.44]
 [ 9285.8  11203.28  8002.84  7269.72]
 [ 7572.48  9514.32  9924.96 10312.4 ]
 [ 6549.36  9150.08  8624.6   6496.  ]]


In [13]:
revenue_per_unit = np.round(daily_sales / units_sold, 2)
print(revenue_per_unit)

category = revenue_per_unit.mean(axis=0)
categories = ['Food', 'Electronics', 'Clothing', 'Furniture']
most_expensive = np.argmax(category)
print(categories[most_expensive])

[[ 93.02  88.61 139.52  72.88]
 [184.82 122.38 106.12  82.49]
 [ 91.61  71.88 101.21  76.99]
 [ 88.49  98.16 144.77  98.65]
 [ 92.09 110.6  149.13 107.33]
 [110.58  83.05 132.96  99.32]
 [ 89.18  90.75  55.8   93.18]
 [135.68 113.62 109.51  78.34]
 [ 67.3  128.16 150.11 141.11]
 [ 78.42  88.63 106.21  86.15]]
Clothing


In [14]:
target = 15000
target_diff = daily_sales - target
print("Difference from target:")
print(target_diff)

food_missed = np.sum(target_diff[:, 0] < 0)
electronics_missed = np.sum(target_diff[:, 1] < 0)
clothing_missed = np.sum(target_diff[:, 2] < 0)
furniture_missed = np.sum(target_diff[:, 3] < 0)

print("Food:", food_missed)
print("Electronics:", electronics_missed)
print("Clothing:", clothing_missed)
print("Furniture:", furniture_missed)

Difference from target:
[[-9140 -6228 -6908 -9534]
 [-5574 -6556 -6829 -7081]
 [-9870 -8315 -9231 -7609]
 [-7567 -8816 -5445 -6615]
 [-5883 -5157 -7096 -9526]
 [-8918 -7442 -7953 -7253]
 [-9025 -8194 -9811 -7266]
 [-6995 -5342 -8101 -8733]
 [-8472 -6798 -6444 -6110]
 [-9354 -7112 -7565 -9400]]
Food: 10
Electronics: 10
Clothing: 10
Furniture: 10


In [15]:
log_sales = np.log(daily_sales)
print(f"Mean of log data: {log_sales.mean():.4f}")
# Why it's useful: Log transformations help normalize highly skewed data distributions,
# making variances more stable and scaling massive outliers down for better modeling.
#Machine learning models often struggle with huge differences.
#Taking the log compresses the numbers.

Mean of log data: 8.8882


In [16]:
weights = np.array([1.0, 0.9, 1.0, 0.95])
weighted_sales = daily_sales * weights
print(weighted_sales)

[[5860.   7894.8  8092.   5192.7 ]
 [9426.   7599.6  8171.   7523.05]
 [5130.   6016.5  5769.   7021.45]
 [7433.   5565.6  9555.   7965.75]
 [9117.   8858.7  7904.   5200.3 ]
 [6082.   6802.2  7047.   7359.65]
 [5975.   6125.4  5189.   7347.3 ]
 [8005.   8692.2  6899.   5953.65]
 [6528.   7381.8  8556.   8445.5 ]
 [5646.   7099.2  7435.   5320.  ]]


### EXERCISE 4

In [17]:
average_sales = daily_sales.mean(axis=0)
print("Average sales:")
print(average_sales)

highest_average = np.max(average_sales)
print(highest_average)

best_category = np.argmax(average_sales)
print(categories[best_category])


Average sales:
[6920.2 8004.  7461.7 7087.3]
8004.0
Electronics


In [18]:
daily_totals = daily_sales.sum(axis=1)
print(daily_totals)

highest_total = np.max(daily_totals)
print("Highest sales:", highest_total)

lowest_total = np.min(daily_totals)
print("Lowest sales:", lowest_total)

best_day = np.argmax(daily_totals)
print("Best sales day:", best_day)

worst_day = np.argmin(daily_totals)
print("Worst sales day:", worst_day)

[28190 33960 24975 31557 32338 28434 25704 30829 32176 26569]
Highest sales: 33960
Lowest sales: 24975
Best sales day: 1
Worst sales day: 2


In [19]:
std_sales = daily_sales.std(axis=0)
print("Standard deviation:")
print(std_sales)

highest_std = np.max(std_sales)
print("Highest standard deviation:", highest_std)

highest_std_index = np.argmax(std_sales)
print("Most volatile category:", categories[highest_std_index])



Standard deviation:
[1422.91769263 1167.90419128 1232.68528425 1211.91749307]
Highest standard deviation: 1422.9176926301816
Most volatile category: Food


In [20]:
electronic_cumsum = daily_sales[:, 1].cumsum()
print(electronic_cumsum)

days = np.where( electronic_cumsum> 400000)[0]
print("Days above 400000:")
print(days)


[ 8772 17216 23901 30085 39928 47486 54292 63950 72152 80040]
Days above 400000:
[]


In [21]:
electronics = daily_sales[:, 1]
daily_total = daily_sales.sum(axis=1)
percentage = (electronics / daily_total) * 100

print("Daily percentages:")
print(percentage)

print("Average percentage:")
print(percentage.mean())

Daily percentages:
[31.11741752 24.86454653 26.76676677 19.59628609 30.43787495 26.58085391
 26.47836913 31.32764605 25.49104923 29.68873499]
Average percentage:
27.234954514883718


### RESHAPING AND BROADCASTING

In [22]:
reshaped_sales = daily_sales.reshape(5, 8)
print(reshaped_sales)

#Yes , the data makes sense since the number of elements remain the same
#The rows represent data from two consecutive days after reshaping

[[5860 8772 8092 5466 9426 8444 8171 7919]
 [5130 6685 5769 7391 7433 6184 9555 8385]
 [9117 9843 7904 5474 6082 7558 7047 7747]
 [5975 6806 5189 7734 8005 9658 6899 6267]
 [6528 8202 8556 8890 5646 7888 7435 5600]]


In [23]:
transposed_sales = daily_sales.T

print("Transposed array:",transposed_sales)

average1 = transposed_sales.mean(axis=1)
print("Average using transpose:")
print(average1)

average2 = daily_sales.mean(axis=0)
print("Average using original array:")
print(average2)

Transposed array: [[5860 9426 5130 7433 9117 6082 5975 8005 6528 5646]
 [8772 8444 6685 6184 9843 7558 6806 9658 8202 7888]
 [8092 8171 5769 9555 7904 7047 5189 6899 8556 7435]
 [5466 7919 7391 8385 5474 7747 7734 6267 8890 5600]]
Average using transpose:
[6920.2 8004.  7461.7 7087.3]
Average using original array:
[6920.2 8004.  7461.7 7087.3]


In [24]:
daily_total = daily_sales.sum(axis=1, keepdims=True)
print("Daily totals:")
print(daily_total)

difference = daily_sales - daily_total
print("Difference:")
print(difference)

Daily totals:
[[28190]
 [33960]
 [24975]
 [31557]
 [32338]
 [28434]
 [25704]
 [30829]
 [32176]
 [26569]]
Difference:
[[-22330 -19418 -20098 -22724]
 [-24534 -25516 -25789 -26041]
 [-19845 -18290 -19206 -17584]
 [-24124 -25373 -22002 -23172]
 [-23221 -22495 -24434 -26864]
 [-22352 -20876 -21387 -20687]
 [-19729 -18898 -20515 -17970]
 [-22824 -21171 -23930 -24562]
 [-25648 -23974 -23620 -23286]
 [-20923 -18681 -19134 -20969]]


In [25]:
bonus_rates = np.array([0.05, 0.08, 0.06, 0.04])

bonuses = daily_sales * bonus_rates
print("Bonuses:", bonuses)

total_bonus = bonuses.sum()
print("Total bonus:", total_bonus)

Bonuses: [[293.   701.76 485.52 218.64]
 [471.3  675.52 490.26 316.76]
 [256.5  534.8  346.14 295.64]
 [371.65 494.72 573.3  335.4 ]
 [455.85 787.44 474.24 218.96]
 [304.1  604.64 422.82 309.88]
 [298.75 544.48 311.34 309.36]
 [400.25 772.64 413.94 250.68]
 [326.4  656.16 513.36 355.6 ]
 [282.3  631.04 446.1  224.  ]]
Total bonus: 17175.239999999998


In [26]:
minimum = daily_sales.min(axis=0)
maximum = daily_sales.max(axis=0)

normalized = (daily_sales - minimum) / (maximum - minimum)
print(normalized)

[[0.16992551 0.70729708 0.66491067 0.        ]
 [1.         0.6176551  0.68300504 0.71641355]
 [0.         0.13692266 0.13284471 0.56220794]
 [0.53608007 0.         1.         0.85251168]
 [0.92807263 1.         0.62185066 0.00233645]
 [0.22160149 0.37551244 0.42556115 0.66617991]
 [0.1966946  0.1699918  0.         0.66238318]
 [0.66922719 0.94943974 0.39166285 0.23393692]
 [0.32541899 0.55151681 0.77118644 1.        ]
 [0.12011173 0.46570101 0.51442968 0.03913551]]


### BOOLEAN INDEXING


In [27]:
electronics_data = daily_sales[:,1]
average = electronics_data.mean()
print("Average:", average)

below_average = electronics_data < average
print(below_average)

days = np.where(below_average)[0]

print("Days below average:")
print(days)

Average: 8004.0
[False False  True  True False  True  True False False  True]
Days below average:
[2 3 5 6 9]


In [28]:
revenue_per_unit = np.round(daily_sales / units_sold, 2)
print(revenue_per_unit)

category = revenue_per_unit.mean(axis=0)
categories = ['Food', 'Electronics', 'Clothing', 'Furniture']
most_expensive = np.argmax(category)
print(categories[most_expensive])

[[ 93.02  88.61 139.52  72.88]
 [184.82 122.38 106.12  82.49]
 [ 91.61  71.88 101.21  76.99]
 [ 88.49  98.16 144.77  98.65]
 [ 92.09 110.6  149.13 107.33]
 [110.58  83.05 132.96  99.32]
 [ 89.18  90.75  55.8   93.18]
 [135.68 113.62 109.51  78.34]
 [ 67.3  128.16 150.11 141.11]
 [ 78.42  88.63 106.21  86.15]]
Clothing


In [29]:
food = daily_sales[:, 0]
clothing = daily_sales[:, 2]

condition = (food > 13000) & (clothing > 9000)

print(daily_sales[condition])

[]


In [30]:
high_units = units_sold > 200
print(high_units)

count = high_units.sum()
print("Number above 200:", count)

[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]
Number above 200: 0


In [31]:
furniture = daily_sales[:, 3]

median = np.median(furniture)
print("Median:", median)

above_median = furniture > median
high_sales = furniture[above_median]
print("Sales above median:")
print(high_sales)

mean_above_median = furniture[above_median].mean()
print(mean_above_median)

overall_mean = furniture.mean()
print(overall_mean)

Median: 7562.5
Sales above median:
[7919 8385 7747 7734 8890]
8135.0
7087.3


In [33]:
totals = daily_sales.sum(axis=1)
print("Daily totals:",totals)

order = np.argsort(totals)
print("Sorted indices:", order)

top_three = order[-3:]
top_three = top_three[::-1]

print("Top 3 days:")
print(top_three)

print(daily_sales[top_three])

Daily totals: [28190 33960 24975 31557 32338 28434 25704 30829 32176 26569]
Sorted indices: [2 6 9 0 5 7 3 8 4 1]
Top 3 days:
[1 4 8]
[[9426 8444 8171 7919]
 [9117 9843 7904 5474]
 [6528 8202 8556 8890]]


### np.Where

In [34]:
flags = np.where(daily_sales > 20000, 1, 0)
print(flags)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [35]:
tiers = np.where(
    clothing > 10000,
    "Premium",
    np.where(clothing >= 7500,"Standard", "Below Target")
)
print(tiers)

['Standard' 'Standard' 'Below Target' 'Standard' 'Standard' 'Below Target'
 'Below Target' 'Below Target' 'Standard' 'Below Target']


In [36]:
average = electronics.mean()

adjusted = np.where(
    electronics < 40000,average,electronics
)
print(adjusted)

[8004. 8004. 8004. 8004. 8004. 8004. 8004. 8004. 8004. 8004.]


In [37]:
flat_sales = daily_sales.ravel()

top5 = np.argsort(flat_sales)[-5:]

top5 = top5[::-1]

rows, cols = np.unravel_index(top5, daily_sales.shape)

categories = ["Food", "Electronics", "Clothing", "Furniture"]

for i in range(len(rows)):
    print(f"Row: {rows[i]}, Column: {cols[i]}, Value: {daily_sales[rows[i], cols[i]]}")

Row: 4, Column: 1, Value: 9843
Row: 7, Column: 1, Value: 9658
Row: 3, Column: 2, Value: 9555
Row: 1, Column: 0, Value: 9426
Row: 4, Column: 0, Value: 9117


In [38]:
food = daily_sales[:, 0]
electronics = daily_sales[:, 1]

new_food = np.where(food > 13000, food * 1.05, food)
new_electronics = np.where(electronics > 48000, electronics * 1.03, electronics)

bonus_sales = daily_sales.astype(float).copy()

bonus_sales[:, 0] = new_food
bonus_sales[:, 1] = new_electronics

print(bonus_sales)

[[5860. 8772. 8092. 5466.]
 [9426. 8444. 8171. 7919.]
 [5130. 6685. 5769. 7391.]
 [7433. 6184. 9555. 8385.]
 [9117. 9843. 7904. 5474.]
 [6082. 7558. 7047. 7747.]
 [5975. 6806. 5189. 7734.]
 [8005. 9658. 6899. 6267.]
 [6528. 8202. 8556. 8890.]
 [5646. 7888. 7435. 5600.]]


### HANDLING NaN

In [39]:
sales = daily_sales.astype(float)

sales[2,1] = np.nan
sales[5,3] = np.nan
sales[8,0] = np.nan

print(sales)

[[5860. 8772. 8092. 5466.]
 [9426. 8444. 8171. 7919.]
 [5130.   nan 5769. 7391.]
 [7433. 6184. 9555. 8385.]
 [9117. 9843. 7904. 5474.]
 [6082. 7558. 7047.   nan]
 [5975. 6806. 5189. 7734.]
 [8005. 9658. 6899. 6267.]
 [  nan 8202. 8556. 8890.]
 [5646. 7888. 7435. 5600.]]


In [40]:
missing = np.isnan(sales)
print(missing)

print("Total missing values:")
print(missing.sum())

print("Missing values in each column:")
print(missing.sum(axis=0))

[[False False False False]
 [False False False False]
 [False  True False False]
 [False False False False]
 [False False False False]
 [False False False  True]
 [False False False False]
 [False False False False]
 [ True False False False]
 [False False False False]]
Total missing values:
3
Missing values in each column:
[1 1 0 1]


In [41]:
print("Mean ignoring NaNs:")
print(np.nanmean(sales,axis=0))

print("Normal mean:")
print(sales.mean(axis=0))

Mean ignoring NaNs:
[6963.77777778 8150.55555556 7461.7        7014.        ]
Normal mean:
[   nan    nan 7461.7    nan]


In [42]:
medians = np.nanmedian(sales,axis=0)

for column in range(sales.shape[1]):
    missing = np.isnan(sales[:,column])
    sales[missing,column] = medians[column]

print(sales)

[[5860. 8772. 8092. 5466.]
 [9426. 8444. 8171. 7919.]
 [5130. 8202. 5769. 7391.]
 [7433. 6184. 9555. 8385.]
 [9117. 9843. 7904. 5474.]
 [6082. 7558. 7047. 7391.]
 [5975. 6806. 5189. 7734.]
 [8005. 9658. 6899. 6267.]
 [6082. 8202. 8556. 8890.]
 [5646. 7888. 7435. 5600.]]


In [43]:
def clean_array(arr):
    arr = arr.astype(float)
    arr[arr==-1] = np.nan

    means = np.nanmean(arr,axis=0)

    for column in range(arr.shape[1]):
        mask = np.isnan(arr[:,column])
        arr[mask,column] = means[column]

    return arr