In [1]:
import numpy as np
fare = np.array([50,70,100,150,200])
print(fare)
print(type(fare))

[ 50  70 100 150 200]
<class 'numpy.ndarray'>


In [6]:
#2 dimensional array
day_fares = np.array([
    [60,80,100],
    [56,89,70],
    [40,50,60],
    ])

print(day_fares)
print(day_fares.shape)

[[ 60  80 100]
 [ 56  89  70]
 [ 40  50  60]]
(3, 3)


In [8]:
# Array of constants
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.full((2, 2),7.5)

array([[7.5, 7.5],
       [7.5, 7.5]])

In [13]:
#Ranges
np.arange(0, 10, 2)


array([0, 2, 4, 6, 8])

In [15]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

Arange is for when you know the step size;linspace is for when you know how many values you want and want them evenly spaced .Staticians use linspace all the time to generate x-values for plotting curves

In [16]:
#Identity matrices
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

1. An array of the numbers 5 to 20 inclusive
2. A 4 by 4 matrix of all threes
3. Ten values evenly spaced between 0 and 1
4. The 5 by 5 identity matrix
5. A 2D array representing a week (7rows) of hourly fares(24 columns) all initialized to zero - you will fill this in later

In [23]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [19]:
np.arange(5, 21, 1)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [5]:
#np.random.randint
#generates random intergers/numbers within a range

#simulate one wheel of random daily customers counts
np.random.seed(42) #for reproducability
customer_counts = np.random.randint(50,101,size = 20)
print(customer_counts)

# 10 by 4 grid of random sales fihure between 50000 and 60000
mock_sales = np.random.randint(50000,60000 , size = (10,4))
print(mock_sales)

[88 78 64 92 57 70 88 68 72 60 60 73 85 89 73 52 71 51 73 93]
[[56949 52433 55311 55051]
 [56420 51184 54555 53385]
 [56396 58666 59274 52558]
 [57849 52047 52747 59167]
 [59998 50189 52734 53005]
 [54658 51899 57734 51267]
 [51528 53556 53890 58838]
 [55393 58792 58433 57513]
 [52612 57041 59555 56235]
 [55486 57099 59670 50775]]


In [ ]:
#np.random.normal()
#generates random numbers from a normal(gaussian) distribution
#generates numbers clustered around a mean, with most values 
#this is how most real world quantities are distributed

In [6]:
np.random.seed(42)
normal_data = np.random.normal(100,15,1000)
print(normal_data)

#stimulate 10 days of food sales;average 13000,spread 1500
np.random.seed(42)
food_sales_sim = np.random.normal(loc=13000,scale=1500,size=(10))
print(food_sales_sim.round(0))

#stimulate elextronics; higer mean more volatile(wide spread)
electronics_sim = np.random.normal(loc=45700,scale=5000,size=(10))
print(electronics_sim)

[107.4507123   97.92603548 109.71532807 122.84544785  96.48769938
  96.48794565 123.68819223 111.51152094  92.95788421 108.13840065
  93.04873461  93.0140537  103.62943407  71.30079633  74.12623251
  91.56568706  84.80753319 104.71370999  86.37963887  78.81544448
 121.98473153  96.61335549 101.01292307  78.62877721  91.83425913
 101.66383885  82.73509634 105.63547028  90.99041965  95.62459375
  90.97440082 127.78417277  99.79754163  84.13433607 112.33817368
  81.68734525 103.13295393  70.60494814  80.07720927 102.95291854
 111.0769987  102.57052422  98.26527576  95.48344457  77.82217014
  89.20233687  93.09041844 115.85683339 105.15427434  73.55439767
 104.86125954  94.22376579  89.84617    109.17514433 115.46499284
 113.96920179  87.41173715  95.36181436 104.96895147 114.63317691
  92.81238643  97.21511535  83.40497539  82.05690064 112.18788734
 120.34360043  98.91984818 115.05299347 105.42454038  90.32320368
 105.42093408 123.0705485   99.46260941 123.46965484  60.70382344
 112.32853

### Understanding Array Properties

In [10]:
#.shape 
#Returns a tuple telling the size of each dimension of the array
#Tells us the rows and columns of the array

print(mock_sales.shape)
print(f"Days:{mock_sales.shape[0]}")
print(f"Products:{mock_sales.shape[1]}")



(10, 4)
Days:10
Products:4


In [16]:
#3 for a 3D array(tensor)/cube for data
print(mock_sales.ndim)

prices = np.array([10,20,30,40,50])
print(prices.ndim)

#imagine 5 weeks of data ; each week has 10 days and 4 categories
five_weeks = np.zeros((5,10,4))
print(five_weeks.ndim)
print(five_weeks.shape)
print(five_weeks)

2
1
3
(5, 10, 4)
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [12]:
#size
#returns the total number of elements in an array
print(mock_sales.size)
print(mock_sales.shape[0]*mock_sales.shape[1])
print(mock_sales.shape)

40
40
(10, 4)


### Indexing and Slicing
Indexing means grabbing a single element
Slicing means grabbing a subset


In [ ]:
# 1D indexing and slicing
# Here we give one index in the square brackets and it will return the entire row of that index
#Average sales per day
average_daily_sales = np.mean(mock_sales,axis = 0)
print(average_daily_sales)

#Access by position
print(average_daily_sales[0]) # first column
print(average_daily_sales[-1]) # last column
print(average_daily_sales[1:3]) # second and third column

#Slicing : syntax 
#Stop is exclusive - the element that index is not included in the slice
#Stop is optional - if not provided , it will default to one
print(average_daily_sales[:2]) #first two columns
print(average_daily_sales[::2]) # every other column
print(average_daily_sales[:-1]) #reverse the array


[55728.9 54290.6 56390.3 54779.4]
55728.9
54779.4
[54290.6 56390.3]
[55728.9 54290.6]
[55728.9 56390.3]
[55728.9 54290.6 56390.3]


### 2D indexing and slicing
Here we need two indices: [row,column].The comma separates them
A colon by itself means "all of them"

In [ ]:
#single element : mock sales{row,column}
print(mock_sales)

print(mock_sales[0,0]) #first row, first column
print(mock_sales[0,1]) # first row , second column
print(mock_sales[-1,-1]) # last row , last column

#entire row: daily sales for the first day
print(mock_sales[0,:]) #first row , all columns

#entire column: daily sales for the first product
first_product_sales = mock_sales[:,0] 
print(first_product_sales)

#subgrid: first 3 days , first 2 products
print(mock_sales[:3,:2])

#last 3 days , last 2 products
print(mock_sales[-3:,-2:])

#entire other days , all categories
alternate_days_sales = mock_sales[-3:,-2:]
print(alternate_days_sales)
print(alternate_days_sales.shape)

#NB
#Slices are vies , not copies . If you modify a slice , use the copy() method. If you want an independent version ; subgrid 

#proof that slicing shares memory with the original array
view = mock_sales[:2, :]
view[0,0] = 9999
print(mock_sales[0,0])

#safer version using copy()
mock_sales[0,0] = 5000 #Resetting the value back to original for demonstration
safe_copy = mock_sales[:2,:].copy()
safe_copy[0,0] = 9999
print(mock_sales[0,0])
print(safe_copy[0,0])
print(mock_sales)
print(safe_copy)

[[56949 52433 55311 55051]
 [56420 51184 54555 53385]
 [56396 58666 59274 52558]
 [57849 52047 52747 59167]
 [59998 50189 52734 53005]
 [54658 51899 57734 51267]
 [51528 53556 53890 58838]
 [55393 58792 58433 57513]
 [52612 57041 59555 56235]
 [55486 57099 59670 50775]]
56949
52433
50775
[56949 56420 56396 57849 59998 54658 51528 55393 52612 55486]
[56949 56420 56396 57849 59998 54658 51528 55393 52612 55486]
[56949 56420 56396 57849 59998 54658 51528 55393 52612 55486]
[[56949 52433]
 [56420 51184]
 [56396 58666]]
[[58433 57513]
 [59555 56235]
 [59670 50775]]
[[58433 57513]
 [59555 56235]
 [59670 50775]]
(3, 2)
9999
5000
9999
[[ 5000 52433 55311 55051]
 [56420 51184 54555 53385]
 [56396 58666 59274 52558]
 [57849 52047 52747 59167]
 [59998 50189 52734 53005]
 [54658 51899 57734 51267]
 [51528 53556 53890 58838]
 [55393 58792 58433 57513]
 [52612 57041 59555 56235]
 [55486 57099 59670 50775]]
[[ 9999 52433 55311 55051]
 [56420 51184 54555 53385]]


### Vectorized operations


In [ ]:
#Elementwise operstions
# these operations are perfomed on each element of the array

#1.Scalar operations: Adding , subtracting , multiplying or dividing
#Apply 16% on VAT 
products_with_vat = mock_sales * 1.6
print(products_with_vat[0])
print(products_with_vat[2])
print(products_with_vat[7])

#subtract a fixed overhead of ksh 1000 per product
net_profit = mock_sales - 1000
print(net_profit)


[ 8000.  83892.8 88497.6 88081.6]
[90233.6 93865.6 94838.4 84092.8]
[88628.8 94067.2 93492.8 92020.8]
[[ 4000 51433 54311 54051]
 [55420 50184 53555 52385]
 [55396 57666 58274 51558]
 [56849 51047 51747 58167]
 [58998 49189 51734 52005]
 [53658 50899 56734 50267]
 [50528 52556 52890 57838]
 [54393 57792 57433 56513]
 [51612 56041 58555 55235]
 [54486 56099 58670 49775]]


In [20]:
# Array + array =same shape
#total revenue combining sales of all products for each day
online = mock_sales * 0.4
offline = mock_sales * 0.6
total_revenue = online + offline

print(online)
print('-------------------------------------')
print(offline)
print('-------------------------------------')
print(total_revenue)

[[ 2000.  20973.2 22124.4 22020.4]
 [22568.  20473.6 21822.  21354. ]
 [22558.4 23466.4 23709.6 21023.2]
 [23139.6 20818.8 21098.8 23666.8]
 [23999.2 20075.6 21093.6 21202. ]
 [21863.2 20759.6 23093.6 20506.8]
 [20611.2 21422.4 21556.  23535.2]
 [22157.2 23516.8 23373.2 23005.2]
 [21044.8 22816.4 23822.  22494. ]
 [22194.4 22839.6 23868.  20310. ]]
-------------------------------------
[[ 3000.  31459.8 33186.6 33030.6]
 [33852.  30710.4 32733.  32031. ]
 [33837.6 35199.6 35564.4 31534.8]
 [34709.4 31228.2 31648.2 35500.2]
 [35998.8 30113.4 31640.4 31803. ]
 [32794.8 31139.4 34640.4 30760.2]
 [30916.8 32133.6 32334.  35302.8]
 [33235.8 35275.2 35059.8 34507.8]
 [31567.2 34224.6 35733.  33741. ]
 [33291.6 34259.4 35802.  30465. ]]
-------------------------------------
[[ 5000. 52433. 55311. 55051.]
 [56420. 51184. 54555. 53385.]
 [56396. 58666. 59274. 52558.]
 [57849. 52047. 52747. 59167.]
 [59998. 50189. 52734. 53005.]
 [54658. 51899. 57734. 51267.]
 [51528. 53556. 53890. 58838.]
 [553

In [6]:
#Universal functions(ufuncs)
#These are numpy functions that operate elementwise on arrays
np.random.normal(loc=13000,scale=1500,size=(10,4))

arr1 = np.array([10, 20, 30])
arr2 = np.array([1, 2, 3])
result = np.add(arr1, arr2)
print(result)

print("----------------------------------")

arr1 = np.array([10, 20, 30])
arr2 = np.array([1, 2, 3])
result = np.subtract(arr1, arr2)
print(result)

print("----------------------------------")

arr1 = np.array([2, 4, 6])
arr2 = np.array([3, 5, 7])
result = np.multiply(arr1, arr2)
print(result)

print("----------------------------------")

arr1 = np.array([10, 20, 30])
arr2 = np.array([2, 4, 5])
result = np.divide(arr1, arr2)
print(result)

print("----------------------------------")

arr = np.array([4, 9, 16, 25])
result = np.sqrt(arr)
print(result)

print("----------------------------------")

arr = np.array([1, np.e, np.e**2])
result = np.log(arr)
print(result)

print("----------------------------------")

arr = np.array([3.14159, 2.71828, 6.78945])
result = np.round(arr, 2)
print(result)



[11 22 33]
----------------------------------
[ 9 18 27]
----------------------------------
[ 6 20 42]
----------------------------------
[5. 5. 6.]
----------------------------------
[2. 3. 4. 5.]
----------------------------------
[0. 1. 2.]
----------------------------------
[3.14 2.72 6.79]


### Aggregation and Axis Concepts
Aggregation collapses an array into one or more summary values
Total , average, minimums and so on
The axis parameter controls which direction you collapse

In [7]:
# Basic Aggregation
# Sum of all values in the entire array

import numpy as np
#100 days of sales data across 4 categories
#rows = days , columns = categories

np.random.seed(42)
daily_sales = np.random.normal(loc=13000,scale=1500,size=(10,4)).round().astype(int)
print(daily_sales.shape)

#sum of all values in the entire array
print(daily_sales.sum())

#product of elements(useful for growth rates)
growth_rates = np.array([1.0, 1.02, 1.05, 0.98, 1.03])
compound = growth_rates.prod()
print(f"Compound effect: {compound:.4f}")

#cumulative sum-running total of food sales over 10 days
food_cumsum = daily_sales[:,0].cumsum()
print("Running food revenue:",food_cumsum)

#cumulative product
rates = np.array([1.0, 1.02, 1.05, 0.98, 1.03])
print("Compound after each period:",rates.cumprod(),round(4))


(10, 4)
506882
Compound effect: 1.0811
Running food revenue: [ 13745  26394  38690  52053  63534  78732  90915 103014 115994 129307]
Compound after each period: [1.        1.02      1.071     1.04958   1.0810674] 4


#### Statistical aggregation

In [ ]:
food_sales = daily_sales[:,0] #all 10 days of food

#Mean
print(f"Mean food sales :{food_sales.mean():.0f}")

#Median
print(f"Median food sales :{np.median(food_sales):.0f}")

#Standard deviation
print(f"Std dev:{food_sales.std():.0f}")

#Variance(std squared)
print(f"Variance:{food_sales.var():.0f}")

#Min and max
print(f"Lowest day:{food_sales.min()}")
print(f"Highest day:{food_sales.max()}")

print(f"Best day:")

Mean food sales :12931
Median food sales :12814
Std dev:999
Variance:997381
Lowest day:11481
Highest day:15198


#### Axis Concept
Axis controls which direction numpy collapses when it aggregates
axis = 0 collapses the row , one result per column , axis = 1 collapses across the columns , one result per row

In [9]:
average_per_category = daily_sales.mean(axis=0)
print("Average per category:",average_per_category)

total_per_day= daily_sales.sum(axis=1)
print("Total per day:",total_per_day)

#min per column(worst day per category)
worst_per_category = daily_sales.min(axis = 0)
print("Worst per category:",worst_per_category)

#max per column(best day per category)
best_cat_per_day = daily_sales.max(axis = 1)
print("Best category per day:",best_cat_per_day)

Average per category: [12930.7 12271.9 12541.1 12944.5]
Total per day: [55795 54818 50716 46063 47472 51823 50187 52536 49796 47676]
Worst per category: [11481 10060 10413 10863]
Best category per day: [15285 15369 13814 13363 13471 15198 13564 15778 14234 13313]


### Reshaping and broadcasting
Reshape{} Arranges an array into a new shape
          The total number of elements must stay the same
          
Flatten{}
Ravel{}
Broadcasting{}

In [ ]:
print(daily_sales.shape)

#reshape to 8 rows by 5 columns
reshaped = daily_sales.reshape(8,5)
print(reshaped.shape)

# Use -1 to let numpy calculate one dimention automatically 
as_2cols = daily_sales.reshape(-1,2)
print(as_2cols.shape)


(10, 4)
(8, 5)
(20, 2)


In [13]:
print(daily_sales.shape)

#flatten to 1 - all 40 values in one line
flat = daily_sales.reshape(-1)
print(flat.shape)

(10, 4)
(40,)


In [14]:
# Transpose
print(daily_sales.shape)  # (10 , 4)-10 days 4 categories

transposed = daily_sales.T    # (4 , 10) 4 categories , 10 days
print(transposed.shape)

#now transposed[0]is all 10 days for food
print(transposed[0])

#transposed [1] is all electronic days
print(transposed[1])


(10, 4)
(4, 10)
[13745 12649 12296 13363 11481 15198 12183 12099 12980 13313]
[12793 12649 13814 10130 13471 12661 13166 12562 11413 10060]


### Boolean indexing(Filtering)
Lets you select elements based on a condition . Numpy evaluates the conditiom , createsa True/False array (a mask) and returns only the elements where the condition is true

In [22]:
food_sales = daily_sales[:,0]

#which day had food sales above 10000
mask = food_sales > 13000
print(mask)

# use the mask to get just those values
high_food_days = food_sales[mask]
print(high_food_days)

#shortcut
print(food_sales[food_sales > 13000])

#how many days exceeded the target
print((food_sales > 13000).sum)

#what percentage of days
print((food_sales > 13000).mean() * 100)

[ True False False  True False  True False False False  True]
[13745 13363 15198 13313]
[13745 13363 15198 13313]
<built-in method sum of numpy.ndarray object at 0x0000014920B324F0>
40.0


### Multiple Conditions:(AND) (OR) (NOT)

In [27]:
#AND - both conditions must be true
good_days = daily_sales[(daily_sales[:,0] > 13000) & (daily_sales[:, 1] > 35000)]
print(good_days)

normal_food = food_sales[~(food_sales > 14000)]
print(normal_food)

[]
[13745 12649 12296 13363 11481 12183 12099 12980 13313]


### NP.WHERE : Conditional logic on arrays

In [23]:
#np.where(condion , value if true , value if false)
# Was each day's food sales above 13000? Mark it 'high' or 'low'
food_sales = daily_sales[:,0]
food_label = np.where(food_sales > 13000 ,'high','low')
print(food_label)

#return numeric values
food_flag = np.where(food_sales > 13000 , 1, 0)
print(food_flag)

#keep values above threshold , replace others with the threshold
floor_13k = np.where(food_sales < 13000 , 13000 , food_sales)
print(floor_13k)

['high' 'low' 'low' 'high' 'low' 'high' 'low' 'low' 'low' 'high']
[1 0 0 1 0 1 0 0 0 1]
[13745 13000 13000 13363 13000 15198 13000 13000 13000 13313]


## Getting indices - np.where(condition) with one argument
## Nested np.where - multiple categories

### Handling Missing Data(NaN)
It is a special float value that means "there is no valid number here" - it is the absence of a value
Any arithmetic NaN return nAn which i why you have to handle it explicitly


In [24]:
#NaN is a float
print(type(np.nan))

#Arithmetic with NaN always returns NaN
print(5 + np.nan)

#NaN is never equal to itself
print(np.nan == np.nan)

#the right way to check for NaN 
print(np.isnan(np.nan))

<class 'float'>
nan
False
True


In [26]:
# Inserting and detecting NaN
#Simulate a sales dataset with some missing values 
sales = np.array ([
    [12000,4500,np.nan,22000],
    [np.nan,38000,9500,22000],
    [11000,np.nan,7500,25000],
    [15000,41000,11000,np.nan],
])

#Detecting NaN - RETURNS A TRUE OR A FALSE ARRAY
nan_mask = np.isnan(sales)
print(nan_mask)

#Counting missing values in total
print(f"total missing:{nan_mask.sum()}")

#Counting missing per column(axis = 0)
print("missing per category:",nan_mask.sum(axis = 0))

#Counting missing per row(axis = 1)
print("missing per day:",nan_mask.sum(axis = 1))

[[False False  True False]
 [ True False False False]
 [False  True False False]
 [False False False  True]]
total missing:4
missing per category: [1 1 1 1]
missing per day: [1 1 1 1]


# Replace specific values with NaN

In [ ]:
#Simulated data where -1 means "sensor not reading"
raw_data = 

#replace -1 with NaN values
clean = np.where(raw_data == -1 , np.nan,raw_data)
print(clean)